// Code generated by entc, DO NOT EDIT.

package release

const (
	// Label holds the string label denoting the release type in the database.
	Label = "release"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// EdgeGame holds the string denoting the game edge name in mutations.
	EdgeGame = "game"
	// Table holds the table name of the release in the database.
	Table = "releases"
	// GameTable is the table the holds the game relation/edge.
	GameTable = "releases"
	// GameInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	GameInverseTable = "games"
	// GameColumn is the table column denoting the game relation/edge.
	GameColumn = "game_releases"
)

// Columns holds all SQL columns for release fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRegion,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "releases"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"game_releases",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
