// Code generated by entc, DO NOT EDIT.

package file

const (
	// Label holds the string label denoting the file type in the database.
	Label = "file"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// EdgeRom holds the string denoting the rom edge name in mutations.
	EdgeRom = "rom"
	// Table holds the table name of the file in the database.
	Table = "files"
	// RomTable is the table the holds the rom relation/edge.
	RomTable = "files"
	// RomInverseTable is the table name for the Rom entity.
	// It exists in this package in order to avoid circular dependency with the "rom" package.
	RomInverseTable = "roms"
	// RomColumn is the table column denoting the rom relation/edge.
	RomColumn = "file_rom"
)

// Columns holds all SQL columns for file fields.
var Columns = []string{
	FieldID,
	FieldPath,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "files"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"file_rom",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
