// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Backend/ent/datafile"
	"Backend/ent/header"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HeaderCreate is the builder for creating a Header entity.
type HeaderCreate struct {
	config
	mutation *HeaderMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (hc *HeaderCreate) SetName(s string) *HeaderCreate {
	hc.mutation.SetName(s)
	return hc
}

// SetDescription sets the "description" field.
func (hc *HeaderCreate) SetDescription(s string) *HeaderCreate {
	hc.mutation.SetDescription(s)
	return hc
}

// SetVersion sets the "version" field.
func (hc *HeaderCreate) SetVersion(s string) *HeaderCreate {
	hc.mutation.SetVersion(s)
	return hc
}

// SetDate sets the "date" field.
func (hc *HeaderCreate) SetDate(s string) *HeaderCreate {
	hc.mutation.SetDate(s)
	return hc
}

// SetAuthor sets the "author" field.
func (hc *HeaderCreate) SetAuthor(s string) *HeaderCreate {
	hc.mutation.SetAuthor(s)
	return hc
}

// SetURL sets the "url" field.
func (hc *HeaderCreate) SetURL(s string) *HeaderCreate {
	hc.mutation.SetURL(s)
	return hc
}

// SetDatafileID sets the "datafile" edge to the Datafile entity by ID.
func (hc *HeaderCreate) SetDatafileID(id int) *HeaderCreate {
	hc.mutation.SetDatafileID(id)
	return hc
}

// SetDatafile sets the "datafile" edge to the Datafile entity.
func (hc *HeaderCreate) SetDatafile(d *Datafile) *HeaderCreate {
	return hc.SetDatafileID(d.ID)
}

// Mutation returns the HeaderMutation object of the builder.
func (hc *HeaderCreate) Mutation() *HeaderMutation {
	return hc.mutation
}

// Save creates the Header in the database.
func (hc *HeaderCreate) Save(ctx context.Context) (*Header, error) {
	var (
		err  error
		node *Header
	)
	if len(hc.hooks) == 0 {
		if err = hc.check(); err != nil {
			return nil, err
		}
		node, err = hc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeaderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hc.check(); err != nil {
				return nil, err
			}
			hc.mutation = mutation
			node, err = hc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(hc.hooks) - 1; i >= 0; i-- {
			mut = hc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HeaderCreate) SaveX(ctx context.Context) *Header {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (hc *HeaderCreate) check() error {
	if _, ok := hc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := hc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New("ent: missing required field \"description\"")}
	}
	if _, ok := hc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New("ent: missing required field \"version\"")}
	}
	if _, ok := hc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New("ent: missing required field \"date\"")}
	}
	if _, ok := hc.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New("ent: missing required field \"author\"")}
	}
	if _, ok := hc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New("ent: missing required field \"url\"")}
	}
	if _, ok := hc.mutation.DatafileID(); !ok {
		return &ValidationError{Name: "datafile", err: errors.New("ent: missing required edge \"datafile\"")}
	}
	return nil
}

func (hc *HeaderCreate) sqlSave(ctx context.Context) (*Header, error) {
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (hc *HeaderCreate) createSpec() (*Header, *sqlgraph.CreateSpec) {
	var (
		_node = &Header{config: hc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: header.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: header.FieldID,
			},
		}
	)
	if value, ok := hc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: header.FieldName,
		})
		_node.Name = value
	}
	if value, ok := hc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: header.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := hc.mutation.Version(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: header.FieldVersion,
		})
		_node.Version = value
	}
	if value, ok := hc.mutation.Date(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: header.FieldDate,
		})
		_node.Date = value
	}
	if value, ok := hc.mutation.Author(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: header.FieldAuthor,
		})
		_node.Author = value
	}
	if value, ok := hc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: header.FieldURL,
		})
		_node.URL = value
	}
	if nodes := hc.mutation.DatafileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   header.DatafileTable,
			Columns: []string{header.DatafileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: datafile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.datafile_header = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HeaderCreateBulk is the builder for creating many Header entities in bulk.
type HeaderCreateBulk struct {
	config
	builders []*HeaderCreate
}

// Save creates the Header entities in the database.
func (hcb *HeaderCreateBulk) Save(ctx context.Context) ([]*Header, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Header, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HeaderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HeaderCreateBulk) SaveX(ctx context.Context) []*Header {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
